#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_REQUEST_SIZE 4096
#define MAX_RESPONSE_SIZE 256

#define MAX_FAILURE_RESPONSE_SIZE 512

#define MAX_FILE_PATH 256

#define EMAIL_SIZE 128
#define PASSWORD_SIZE 128
#define USER_NAME_SIZE 32
#define ID_SIZE 32

#define MIN_EMAIL_SIZE 4
#define MIN_USER_NAME_SIZE 4
#define MIN_PASSWORD_SIZE 4

#define TOKEN_BYTES 32
#define TOKEN_HEX_LEN (TOKEN_BYTES * 2 + 1)

#define HASH_SIZE crypto_pwhash_STRBYTES

#define BIGSERIAL_STRING_LENGTH 21

#define PORT 8080

#define MAX_ERROR_MESSAGE_LENGTH 256

#define TRUE 1
#define FALSE 0

#define MAX_PLAYERS 10
#define MAX_NAME_LENGTH 256
#define MAX_LIVES 3
#define MAX_BULLETS 10
#define BULLET_STATE_COUNT 3
#define MAX_ITEMS 10
#define ITEM_TYPES 11
#define MAX_PLAYER_INPUT 50
#define MAX_NOTE_COUNT 10
#define MAX_NOTE_TEXT_LENGTH 100

#endif