name: Build Shotgun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev libsodium-dev

      - name: Clean build
        run: |
          rm -f shotgun
          make clean || true

      - name: Compile Project
        run: | 
          make -f makefile.mk

      - name: Initialize Test Database
        run: | 
          sudo service postgresql start
          sudo -u postgres createdb shotgun

          sudo -u postgres psql -d shotgun -f database/init.sql
          sudo -u postgres psql -d shotgun -f database/test_init.sql

      - name: Starting up the Server
        run: |
          ./shotgun &
          sleep 5

      - name: Verify Server
        run: |
          curl -v http://localhost:8080/

      - name: Postman Tests
        run: |
          newman run postman/shotgun.postman_collection.json --env-var "host=localhost"
          
          

          
